### ISSUE TITLE
How to get the SearXNG Instance 

### ISSUE THREAD

**Issue by sanjayk0508** [hizkifw/bong#1]
I went in https://searx.space/, and copy-pasted this into my .envrc:

`export SEARX_ENDPOINT=https://searxng.nicfab.eu/searxng/search`

Is this the correct way, I'm getting this error:
`
I will search for the weather in Mumbai
I will extract the temperature information using regex

import re
import requests

url = 'https://www.google.com/search?q=mumbai+temperature'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
response = requests.get(url, headers=headers)
match = re.search(r'(\d+°\sC)', response.text)

if match:
    temperature = match.group()
    print(f"The temperature in Mumbai is {temperature}.")
else:
    print("I could not get the temperature information right now. Please try again later.")
`

**Comment by sanjayk0508** [comment]
I'm getting a response, but I think it's not fetching the present-time internet data:

![Screenshot (205)](https://user-images.githubusercontent.com/102804548/224494981-a987597f-50c4-4ef9-890f-4fb4314e1f1b.png)

**Comment by hizkifw** [comment]
Hi sorry just saw this.

It does that sometimes, it takes a bit of prompting to get it to actually work. I'm still not sure of the best way to prompt it so you'll need to experiment a bit.

As for the endpoint, you should just provide the base URL (`https://searxng.nicfab.eu/`) but it seems like that specific instance doesn't allow you to fetch JSON (see `https://searxng.nicfab.eu/search?q=test&format=json`). You'll need to find an instance that allows JSON.
